FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    iproute2 \
    tcpdump \
    iputils-ping \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir \
    plotly \
    seaborn \
    pandas \
    matplotlib \
    numpy \
    scapy

WORKDIR /app

# Cria diretórios de dados
RUN mkdir -p /data/logs /data/pcap /data/csv /tmp

CMD ["python3", "--version"]
